audio:
  sample_rate: 16000
  audio_file: output.wav

hotkey:
  combination:
    - alt
    - shift_l
  debounce_time_ms: 1000  # milliseconds

whisper:
  model: base

logging:
  file: logs.txt
  level: ERROR
